### ISSUE TITLE
GetFieldsByAppId not returning List field values

### ISSUE THREAD

**Issue by Zack-Larson** [StevanFreeborn/onspring-api-sdk-python#2]
Hi,

I was familiarizing myself with the Onspring-API-SDK, and it seems list values are not coming through. When using the method with my app, it returns a None value rather than what I would assume would be a dictionary or list of values associated with the list field. Here is an example of what I am receiving with the GetFieldsByAppID method:

```python
{
  'appId': 105,
   'id': 2940,
   'isRequired': False,
   'isUnique': False,
   'listId': None,
   'multiplicity': None,
   'name': 'Request Status',
   'outputType': None,
   'status': 'Enabled',
   'type': 'List',
   'values': None
}
```

After writing my own function, I was able to get the values:

```python
{
   'appId': 105,
   'id': 2940,
   'isRequired': False,
   'isUnique': False,
   'listId': 371,
   'multiplicity': 'SingleSelect',
   'name': 'Request Status',
   'status': 'Enabled',
   'type': 'List',
   'values': [
      {
        'color': '#a9abad',
        'id': '407dd80a-049a-4982-9eba-6c755ffca418',
        'name': 'Not Started',
        'sortOrder': 1
      },
      {
        'color': '#005baa',
        'id': '29700d14-78ea-4a95-84d7-8681d752e2e4',
        'name': 'In Process',
        'sortOrder': 2
      },
      {
        'color': '#72b444',
        'id': '78eee623-ea56-4af4-b610-b45f4a6893ff',
        'name': 'Complete',
        'sortOrder': 3
      },
      {
        'color': '#d4311f',
        'id': 'a5269d66-d7e1-429d-b202-2fb1257a1d7c',
        'name': 'Canceled',
        'sortOrder': 4
      }
  ]
}
```

![Screenshot 2024-01-23 at 12 29 46 PM](https://github.com/StevanFreeborn/onspring-api-sdk-python/assets/108420799/34f7096b-8d9c-4002-8476-cd53e3bde10d)

![Screenshot 2024-01-23 at 12 29 40 PM](https://github.com/StevanFreeborn/onspring-api-sdk-python/assets/108420799/68fdb9d9-a4e8-448e-b5ff-4a2520de8478)

**Comment by StevanFreeborn** [comment]
@Zack-Larson oh yep you are 100% right. This is a bug in both the `GetFieldsByAppId` and `GetFieldsByIds` methods.

I'll get that fixed up. I appreciate you calling this out.

Actions:
- [x] Update to check for and include list values, multiplicity, output type, and list id if present in fields object
https://github.com/StevanFreeborn/onspring-api-sdk-python/blob/1656e01fc44287951841173530e1c67a88388da2/src/OnspringApiSdk/OnspringClient.py#L332
https://github.com/StevanFreeborn/onspring-api-sdk-python/blob/1656e01fc44287951841173530e1c67a88388da2/src/OnspringApiSdk/OnspringClient.py#L416

**Comment by StevanFreeborn** [comment]
@Zack-Larson I just published a new release `2.0.1` that should address this:

Github Release: https://github.com/StevanFreeborn/onspring-api-sdk-python/releases/tag/2.0.1
PyPI: https://pypi.org/project/OnspringApiSdk/2.0.1/

If you encounter any other issues let me know.

**Comment by Zack-Larson** [comment]
@StevanFreeborn 
I see them coming through, thank you!

One other question... where is the PrintField method? I have tried calling it under Helpers and Models, and checked the respective definitions, and it does not seem to be present.

Thanks!

**Comment by StevanFreeborn** [comment]
@Zack-Larson oh that method was just something I put in the README.md for the example usages. I didn't actually put it in the package.

Here it is:
https://github.com/StevanFreeborn/onspring-api-sdk-python/blob/master/README.md#L181

**Comment by Zack-Larson** [comment]
Gotcha, sounds good. Appreciate you taking care my issue in a timely manner, too!

**Comment by StevanFreeborn** [comment]
@Zack-Larson of course! Super cool that you decided to give the sdk a go.
